[package]
name = "test_poseidon2_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
risc0-zkvm-platform = { version = "2.2.0", features = ["export-syscalls"] }
